/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/agenda/draft/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    put: operations["agenda_draft_update"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/agenda/preview/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["agenda_preview_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/agenda/versions/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["agenda_versions_retrieve"];
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["agenda_versions_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/agenda/versions/{id}/pdf/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["agenda_versions_pdf_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/availability/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["availability_retrieve"];
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["availability_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/availability/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    patch: operations["availability_partial_update"];
    trace?: never;
  };
  "/api/v1/availability/{id}/cancel/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["availability_cancel_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/dashboard/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["dashboard_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/openapi/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
     *
     *     - YAML: application/vnd.oai.openapi
     *     - JSON: application/vnd.oai.openapi+json
     */
    get: operations["openapi_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/organization/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["organization_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/organization/grants/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["organization_grants_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/organization/grants/{id}/revoke/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["organization_grants_revoke_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/organization/units/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["organization_units_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/organization/units/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    patch: operations["organization_units_partial_update"];
    trace?: never;
  };
  "/api/v1/partners/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["partner_list"];
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["partners_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/partners/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    patch: operations["partners_partial_update"];
    trace?: never;
  };
  "/api/v1/planning/options/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["planning_options_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/planning/preview/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["planning_preview_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/processes/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["processes_list"];
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["processes_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/processes/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["processes_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/processes/{id}/transition/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["processes_transition_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/processes/options/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["processes_options_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/proposals/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["proposal_list"];
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["proposals_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/proposals/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["proposal_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    patch: operations["proposals_partial_update"];
    trace?: never;
  };
  "/api/v1/proposals/{id}/decision/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["proposals_decision_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/proposals/{id}/resubmit/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["proposals_resubmit_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/research-projects/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["research_projects_list"];
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["research_projects_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/research-projects/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["research_projects_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    patch: operations["research_projects_partial_update"];
    trace?: never;
  };
  "/api/v1/research-projects/{id}/items/{resource}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["research_projects_items_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/research-projects/{id}/items/{resource}/{item_pk}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    patch: operations["research_projects_items_partial_update"];
    trace?: never;
  };
  "/api/v1/research-projects/{id}/sections/{section_pk}/transition/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["research_projects_sections_transition_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/research-projects/{id}/transition/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["research_projects_transition_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/research-projects/options/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["research_projects_options_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/session/password/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["session_password_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/task-management/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["task_management_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["tasks_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["tasks_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    patch: operations["tasks_partial_update"];
    trace?: never;
  };
  "/api/v1/tasks/{id}/observations/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["tasks_observations_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks/{id}/progress/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["tasks_progress_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks/{id}/transition/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["tasks_transition_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks/bulk-delete/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["tasks_bulk_delete_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/team/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["team_overview"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/team/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["team_employee"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    patch: operations["team_partial_update"];
    trace?: never;
  };
  "/api/v1/team/{id}/avatar/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["team_avatar_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/team/{id}/tor-document/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["team_tor_document_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["user_list"];
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["users_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["user_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    patch: operations["users_partial_update"];
    trace?: never;
  };
  "/api/v1/users/{id}/deactivate/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["users_deactivate_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{id}/reactivate/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["users_reactivate_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{id}/temporary-password/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["users_temporary_password_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/bulk-action/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["users_bulk_action_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/options/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["users_options_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/visits/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    get: operations["visits_retrieve"];
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["visits_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/visits/{id}/departure/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Authenticate via the relayed Odoo session and normalize RPC failures. */
    post: operations["visits_departure_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description * `programs` - programs
     *     * `administration` - administration
     *     * `research` - research
     * @enum {string}
     */
    AgendaDirectionEnum: "programs" | "administration" | "research";
    AgendaDraft: {
      /** Format: date */
      period_start: string;
      /** Format: date */
      period_end: string;
      /** @default  */
      major_events: string;
      revision?: number | null;
    };
    AgendaGenerate: {
      /** Format: date */
      period_start: string;
      /** Format: date */
      period_end: string;
      agenda_direction: components["schemas"]["AgendaDirectionEnum"];
    };
    Availability: {
      employee_id: number;
      kind: components["schemas"]["KindEnum"];
      /** Format: date */
      start_date: string;
      /** Format: date */
      end_date: string;
      /** @default  */
      note: string;
      revision?: number;
    };
    /** @enum {unknown} */
    BlankEnum: "";
    Cancel: {
      revision: number;
      reason: string;
    };
    /**
     * @description * `SUPPRIMER` - SUPPRIMER
     * @enum {string}
     */
    ConfirmationEnum: "SUPPRIMER";
    /**
     * @description * `accept` - accept
     *     * `reject` - reject
     * @enum {string}
     */
    DecisionEnum: "accept" | "reject";
    EncodedProfileFile: {
      name: string;
      mimetype: string;
      content_base64: string;
    };
    /**
     * @description * `leave` - leave
     *     * `absence` - absence
     *     * `mission` - mission
     * @enum {string}
     */
    KindEnum: "leave" | "absence" | "mission";
    /**
     * @description * `application/pdf` - application/pdf
     *     * `image/jpeg` - image/jpeg
     *     * `image/png` - image/png
     * @enum {string}
     */
    MimetypeEnum: "application/pdf" | "image/jpeg" | "image/png";
    Observation: {
      revision: number;
      message: string;
    };
    OrganizationUnit: {
      code: string;
      short_name: string;
      long_name: string;
      /** @default unit */
      kind: string;
      /** @default 0 */
      display_order: number;
      parent_id?: number | null;
      /** @default true */
      active: boolean;
      state_token?: string;
      reason?: string;
    };
    PartnerWrite: {
      name: string;
      email?: string;
      phone?: string;
      /** @default true */
      active: boolean;
    };
    Password: {
      current_password: string;
      new_password: string;
      new_password_confirmation: string;
    };
    PatchedAvailability: {
      employee_id?: number;
      kind?: components["schemas"]["KindEnum"];
      /** Format: date */
      start_date?: string;
      /** Format: date */
      end_date?: string;
      /** @default  */
      note: string;
      revision?: number;
    };
    PatchedEmployeeProfileUpdate: {
      state_token?: string;
      terms_of_reference?: string;
      avatar?: components["schemas"]["EncodedProfileFile"] | null;
      document?: components["schemas"]["EncodedProfileFile"] | null;
      /** @default false */
      remove_avatar: boolean;
      /** @default false */
      remove_document: boolean;
    };
    PatchedOrganizationUnitUpdate: {
      code?: string;
      short_name?: string;
      long_name?: string;
      /** @default unit */
      kind: string;
      /** @default 0 */
      display_order: number;
      parent_id?: number | null;
      /** @default true */
      active: boolean;
      state_token?: string;
      reason?: string;
    };
    PatchedPartnerUpdate: {
      name?: string;
      email?: string;
      phone?: string;
      /** @default true */
      active: boolean;
      state_token?: string;
    };
    PatchedProposalUpdate: {
      /** Format: date */
      start_date?: string;
      /** Format: date */
      due_date?: string;
      /** Format: decimal */
      estimated_work_days?: string;
      title?: string;
      description?: string;
      action_id?: number | null;
      calendar_id?: number;
      revision?: number;
    };
    PatchedResearchProjectItem: {
      revision?: number;
      values?: {
        [key: string]: unknown;
      };
    };
    PatchedResearchProjectUpdate: {
      name?: string;
      objectives?: string;
      /** @default  */
      institutional_commitments: string;
      /** Format: date */
      date_start?: string | null;
      /** Format: date */
      date_end?: string | null;
      donor_id?: number | null;
      partner_ids?: number[];
      team_user_ids?: number[];
      revision?: number;
    };
    PatchedTaskUpdate: {
      /** Format: date */
      start_date?: string;
      /** Format: date */
      due_date?: string;
      /** Format: decimal */
      estimated_work_days?: string;
      revision?: number;
      title?: string;
      description?: string;
      action_id?: number | null;
    };
    PatchedUserUpdate: {
      /** Format: email */
      email?: string;
      login_alias?: string | null;
      first_name?: string;
      last_name?: string;
      position?: string;
      phone?: string;
      agenda_direction?:
        | components["schemas"]["AgendaDirectionEnum"]
        | components["schemas"]["BlankEnum"];
      /** @default true */
      include_in_direction_agendas: boolean;
      unit_ids?: number[];
      primary_unit_id?: number | null;
      primary_supervisor_id?: number | null;
      /** Format: date */
      organization_effective_date?: string;
      state_token?: string;
    };
    PlanningPreview: {
      calendar_id: number;
      /** Format: date */
      start_date: string;
      source: components["schemas"]["SourceEnum"];
      /** Format: date */
      due_date?: string;
      /** Format: decimal */
      estimated_work_days?: string;
    };
    ProcessCreate: {
      process_type: components["schemas"]["ProcessTypeEnum"];
      origin_department_id: number;
      project_id?: number | null;
      subject: string;
      description: string;
      /**
       * Format: decimal
       * @default 0.00
       */
      amount: string;
      details: {
        [key: string]: unknown;
      };
      documents?: components["schemas"]["ProcessDocument"][];
    };
    ProcessDocument: {
      name: string;
      mimetype: components["schemas"]["MimetypeEnum"];
      content_base64: string;
    };
    ProcessTransition: {
      revision: number;
      action: string;
      /** @default  */
      note: string;
      /** @default  */
      confirmation: string;
    };
    /**
     * @description * `fund` - fund
     *     * `purchase` - purchase
     *     * `absence` - absence
     *     * `mission` - mission
     *     * `payment_notice` - payment_notice
     *     * `visa` - visa
     *     * `data` - data
     * @enum {string}
     */
    ProcessTypeEnum:
      | "fund"
      | "purchase"
      | "absence"
      | "mission"
      | "payment_notice"
      | "visa"
      | "data";
    Progress: {
      revision: number;
      /** Format: date */
      entry_date?: string;
      percentage: number;
      /** @default  */
      note: string;
      /** @default false */
      blocked: boolean;
    };
    ProjectSectionTransition: {
      revision: number;
      action: components["schemas"]["ProjectSectionTransitionActionEnum"];
      /** @default  */
      reason: string;
      /** @default  */
      confirmation: string;
    };
    /**
     * @description * `submit` - submit
     *     * `verify` - verify
     *     * `correct` - correct
     *     * `validate` - validate
     *     * `close` - close
     * @enum {string}
     */
    ProjectSectionTransitionActionEnum:
      "submit" | "verify" | "correct" | "validate" | "close";
    ProposalCreate: {
      /** Format: date */
      start_date: string;
      /** Format: date */
      due_date: string;
      /** Format: decimal */
      estimated_work_days: string;
      title: string;
      description: string;
      action_id?: number | null;
      calendar_id: number;
    };
    ProposalDecision: {
      revision: number;
      decision: components["schemas"]["DecisionEnum"];
      /** @default  */
      reason: string;
    };
    ResearchProjectCreate: {
      name: string;
      objectives: string;
      /** @default  */
      institutional_commitments: string;
      /** Format: date */
      date_start?: string | null;
      /** Format: date */
      date_end?: string | null;
      donor_id?: number | null;
      partner_ids?: number[];
      team_user_ids?: number[];
    };
    ResearchProjectItem: {
      revision: number;
      values: {
        [key: string]: unknown;
      };
    };
    ResearchProjectTransition: {
      revision: number;
      action: components["schemas"]["ResearchProjectTransitionActionEnum"];
      lead_id?: number | null;
      /** @default  */
      reason: string;
    };
    /**
     * @description * `approve` - approve
     *     * `reject` - reject
     *     * `close` - close
     *     * `archive` - archive
     * @enum {string}
     */
    ResearchProjectTransitionActionEnum:
      "approve" | "reject" | "close" | "archive";
    Revision: {
      revision: number;
    };
    RevokeGrant: {
      reason: string;
    };
    RoleGrant: {
      user_id: number;
      department_id: number;
      role_code: string;
      scope: components["schemas"]["ScopeEnum"];
      /** Format: date-time */
      valid_from: string;
      /** Format: date-time */
      valid_until?: string | null;
      reason: string;
    };
    /**
     * @description * `unit` - unit
     *     * `tree` - tree
     * @enum {string}
     */
    ScopeEnum: "unit" | "tree";
    /**
     * @description * `workload` - workload
     *     * `due` - due
     * @enum {string}
     */
    SourceEnum: "workload" | "due";
    StateToken: {
      state_token: string;
    };
    TaskBulkDelete: {
      assignments: components["schemas"]["TaskSelection"][];
      reason: string;
      confirmation: components["schemas"]["ConfirmationEnum"];
    };
    TaskCreate: {
      /** Format: date */
      start_date: string;
      /** Format: date */
      due_date: string;
      /** Format: decimal */
      estimated_work_days: string;
      title: string;
      description: string;
      employee_id: number;
      action_id?: number | null;
      calendar_id: number;
    };
    TaskSelection: {
      id: number;
      revision: number;
    };
    Transition: {
      revision: number;
      transition: components["schemas"]["TransitionEnum"];
      /** @default  */
      reason: string;
    };
    /**
     * @description * `validate` - validate
     *     * `reject` - reject
     *     * `close_early` - close_early
     * @enum {string}
     */
    TransitionEnum: "validate" | "reject" | "close_early";
    UserBulkAction: {
      action: components["schemas"]["UserBulkActionActionEnum"];
      users: components["schemas"]["UserSelection"][];
      reason?: string;
      /** @default  */
      confirmation: string;
    };
    /**
     * @description * `deactivate` - deactivate
     *     * `delete` - delete
     * @enum {string}
     */
    UserBulkActionActionEnum: "deactivate" | "delete";
    UserSelection: {
      id: number;
      state_token: string;
    };
    UserWrite: {
      /** Format: email */
      email: string;
      login_alias?: string | null;
      first_name?: string;
      last_name?: string;
      position?: string;
      phone?: string;
      agenda_direction?:
        | components["schemas"]["AgendaDirectionEnum"]
        | components["schemas"]["BlankEnum"];
      /** @default true */
      include_in_direction_agendas: boolean;
      unit_ids?: number[];
      primary_unit_id?: number | null;
      primary_supervisor_id?: number | null;
      /** Format: date */
      organization_effective_date: string;
      state_token?: string;
    };
    Visit: {
      party_size: number;
      visitor_names?: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  agenda_draft_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AgendaDraft"];
        "application/x-www-form-urlencoded": components["schemas"]["AgendaDraft"];
        "multipart/form-data": components["schemas"]["AgendaDraft"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  agenda_preview_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  agenda_versions_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  agenda_versions_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AgendaGenerate"];
        "application/x-www-form-urlencoded": components["schemas"]["AgendaGenerate"];
        "multipart/form-data": components["schemas"]["AgendaGenerate"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  agenda_versions_pdf_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/pdf": string;
        };
      };
    };
  };
  availability_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  availability_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Availability"];
        "application/x-www-form-urlencoded": components["schemas"]["Availability"];
        "multipart/form-data": components["schemas"]["Availability"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  availability_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedAvailability"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedAvailability"];
        "multipart/form-data": components["schemas"]["PatchedAvailability"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  availability_cancel_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Cancel"];
        "application/x-www-form-urlencoded": components["schemas"]["Cancel"];
        "multipart/form-data": components["schemas"]["Cancel"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  dashboard_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  openapi_retrieve: {
    parameters: {
      query?: {
        format?: "json" | "yaml";
        lang?:
          | "af"
          | "ar"
          | "ar-dz"
          | "ast"
          | "az"
          | "be"
          | "bg"
          | "bn"
          | "br"
          | "bs"
          | "ca"
          | "ckb"
          | "cs"
          | "cy"
          | "da"
          | "de"
          | "dsb"
          | "el"
          | "en"
          | "en-au"
          | "en-gb"
          | "eo"
          | "es"
          | "es-ar"
          | "es-co"
          | "es-mx"
          | "es-ni"
          | "es-ve"
          | "et"
          | "eu"
          | "fa"
          | "fi"
          | "fr"
          | "fy"
          | "ga"
          | "gd"
          | "gl"
          | "he"
          | "hi"
          | "hr"
          | "hsb"
          | "hu"
          | "hy"
          | "ia"
          | "id"
          | "ig"
          | "io"
          | "is"
          | "it"
          | "ja"
          | "ka"
          | "kab"
          | "kk"
          | "km"
          | "kn"
          | "ko"
          | "ky"
          | "lb"
          | "lt"
          | "lv"
          | "mk"
          | "ml"
          | "mn"
          | "mr"
          | "ms"
          | "my"
          | "nb"
          | "ne"
          | "nl"
          | "nn"
          | "os"
          | "pa"
          | "pl"
          | "pt"
          | "pt-br"
          | "ro"
          | "ru"
          | "sk"
          | "sl"
          | "sq"
          | "sr"
          | "sr-latn"
          | "sv"
          | "sw"
          | "ta"
          | "te"
          | "tg"
          | "th"
          | "tk"
          | "tr"
          | "tt"
          | "udm"
          | "ug"
          | "uk"
          | "ur"
          | "uz"
          | "vi"
          | "zh-hans"
          | "zh-hant";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/vnd.oai.openapi": {
            [key: string]: unknown;
          };
          "application/yaml": {
            [key: string]: unknown;
          };
          "application/vnd.oai.openapi+json": {
            [key: string]: unknown;
          };
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  organization_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  organization_grants_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RoleGrant"];
        "application/x-www-form-urlencoded": components["schemas"]["RoleGrant"];
        "multipart/form-data": components["schemas"]["RoleGrant"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  organization_grants_revoke_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RevokeGrant"];
        "application/x-www-form-urlencoded": components["schemas"]["RevokeGrant"];
        "multipart/form-data": components["schemas"]["RevokeGrant"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  organization_units_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrganizationUnit"];
        "application/x-www-form-urlencoded": components["schemas"]["OrganizationUnit"];
        "multipart/form-data": components["schemas"]["OrganizationUnit"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  organization_units_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedOrganizationUnitUpdate"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedOrganizationUnitUpdate"];
        "multipart/form-data": components["schemas"]["PatchedOrganizationUnitUpdate"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  partner_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  partners_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PartnerWrite"];
        "application/x-www-form-urlencoded": components["schemas"]["PartnerWrite"];
        "multipart/form-data": components["schemas"]["PartnerWrite"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  partners_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedPartnerUpdate"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedPartnerUpdate"];
        "multipart/form-data": components["schemas"]["PatchedPartnerUpdate"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  planning_options_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  planning_preview_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlanningPreview"];
        "application/x-www-form-urlencoded": components["schemas"]["PlanningPreview"];
        "multipart/form-data": components["schemas"]["PlanningPreview"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  processes_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  processes_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProcessCreate"];
        "application/x-www-form-urlencoded": components["schemas"]["ProcessCreate"];
        "multipart/form-data": components["schemas"]["ProcessCreate"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  processes_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  processes_transition_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProcessTransition"];
        "application/x-www-form-urlencoded": components["schemas"]["ProcessTransition"];
        "multipart/form-data": components["schemas"]["ProcessTransition"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  processes_options_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  proposal_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  proposals_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProposalCreate"];
        "application/x-www-form-urlencoded": components["schemas"]["ProposalCreate"];
        "multipart/form-data": components["schemas"]["ProposalCreate"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  proposal_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  proposals_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedProposalUpdate"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedProposalUpdate"];
        "multipart/form-data": components["schemas"]["PatchedProposalUpdate"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  proposals_decision_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProposalDecision"];
        "application/x-www-form-urlencoded": components["schemas"]["ProposalDecision"];
        "multipart/form-data": components["schemas"]["ProposalDecision"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  proposals_resubmit_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Revision"];
        "application/x-www-form-urlencoded": components["schemas"]["Revision"];
        "multipart/form-data": components["schemas"]["Revision"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  research_projects_list: {
    parameters: {
      query?: {
        /**
         * @description * `active` - active
         *     * `archived` - archived
         */
        status?: "active" | "archived";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  research_projects_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResearchProjectCreate"];
        "application/x-www-form-urlencoded": components["schemas"]["ResearchProjectCreate"];
        "multipart/form-data": components["schemas"]["ResearchProjectCreate"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  research_projects_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  research_projects_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedResearchProjectUpdate"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedResearchProjectUpdate"];
        "multipart/form-data": components["schemas"]["PatchedResearchProjectUpdate"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  research_projects_items_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
        resource: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResearchProjectItem"];
        "application/x-www-form-urlencoded": components["schemas"]["ResearchProjectItem"];
        "multipart/form-data": components["schemas"]["ResearchProjectItem"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  research_projects_items_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
        item_pk: number;
        resource: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedResearchProjectItem"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedResearchProjectItem"];
        "multipart/form-data": components["schemas"]["PatchedResearchProjectItem"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  research_projects_sections_transition_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
        section_pk: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectSectionTransition"];
        "application/x-www-form-urlencoded": components["schemas"]["ProjectSectionTransition"];
        "multipart/form-data": components["schemas"]["ProjectSectionTransition"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  research_projects_transition_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResearchProjectTransition"];
        "application/x-www-form-urlencoded": components["schemas"]["ResearchProjectTransition"];
        "multipart/form-data": components["schemas"]["ResearchProjectTransition"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  research_projects_options_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  session_password_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Password"];
        "application/x-www-form-urlencoded": components["schemas"]["Password"];
        "multipart/form-data": components["schemas"]["Password"];
      };
    };
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  task_management_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  tasks_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskCreate"];
        "application/x-www-form-urlencoded": components["schemas"]["TaskCreate"];
        "multipart/form-data": components["schemas"]["TaskCreate"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  tasks_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  tasks_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedTaskUpdate"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedTaskUpdate"];
        "multipart/form-data": components["schemas"]["PatchedTaskUpdate"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  tasks_observations_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Observation"];
        "application/x-www-form-urlencoded": components["schemas"]["Observation"];
        "multipart/form-data": components["schemas"]["Observation"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  tasks_progress_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Progress"];
        "application/x-www-form-urlencoded": components["schemas"]["Progress"];
        "multipart/form-data": components["schemas"]["Progress"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  tasks_transition_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Transition"];
        "application/x-www-form-urlencoded": components["schemas"]["Transition"];
        "multipart/form-data": components["schemas"]["Transition"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  tasks_bulk_delete_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskBulkDelete"];
        "application/x-www-form-urlencoded": components["schemas"]["TaskBulkDelete"];
        "multipart/form-data": components["schemas"]["TaskBulkDelete"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  team_overview: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  team_employee: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  team_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedEmployeeProfileUpdate"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedEmployeeProfileUpdate"];
        "multipart/form-data": components["schemas"]["PatchedEmployeeProfileUpdate"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  team_avatar_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
    };
  };
  team_tor_document_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
    };
  };
  user_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  users_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserWrite"];
        "application/x-www-form-urlencoded": components["schemas"]["UserWrite"];
        "multipart/form-data": components["schemas"]["UserWrite"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  user_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  users_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedUserUpdate"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedUserUpdate"];
        "multipart/form-data": components["schemas"]["PatchedUserUpdate"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  users_deactivate_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StateToken"];
        "application/x-www-form-urlencoded": components["schemas"]["StateToken"];
        "multipart/form-data": components["schemas"]["StateToken"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  users_reactivate_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StateToken"];
        "application/x-www-form-urlencoded": components["schemas"]["StateToken"];
        "multipart/form-data": components["schemas"]["StateToken"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  users_temporary_password_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StateToken"];
        "application/x-www-form-urlencoded": components["schemas"]["StateToken"];
        "multipart/form-data": components["schemas"]["StateToken"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  users_bulk_action_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserBulkAction"];
        "application/x-www-form-urlencoded": components["schemas"]["UserBulkAction"];
        "multipart/form-data": components["schemas"]["UserBulkAction"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  users_options_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  visits_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  visits_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Visit"];
        "application/x-www-form-urlencoded": components["schemas"]["Visit"];
        "multipart/form-data": components["schemas"]["Visit"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  visits_departure_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Revision"];
        "application/x-www-form-urlencoded": components["schemas"]["Revision"];
        "multipart/form-data": components["schemas"]["Revision"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
}
